sudo: required
dist: trusty

language: cpp
compiler:
- g++
- clang

os:
- linux
- osx

env:
  - secure: "s9BFBAgD-orOfPnM8llK2w"

git:
  submodules: false

before_script:
- ./build_travis.sh

script:
- ./build.sh

addons:
  coverity_scan:
  project:
  name: "QiumingLu/saber"
  description: "Build submitted via Travis CI"
  notification_email: mirantslu@gmail.com
  build_command_prepend: "./build_travis.sh"
  build_command: "./build.sh"
  branch_pattern: master